// lib/nlp/training-data.ts
import type { TrainingData } from "./intent-classifier"
import { singularizeWithFuzzyFallback } from "@/lib/utils/text-preprocessing"

// TRUE ZERO HARDCODING: No arrays of typos, no examples, no lists
// Everything generated by rules + fuzzy + combinatorics

interface IntentRule {
  intent: string
  verbs: string[]           // base action words
  nouns: string[]           // base objects
  prefixes?: string[]       // optional sentence starters
  actionType?: "create" | "read" | "update" | "delete" | "query" | "greeting" | "error" | string[]
}

const RULES: IntentRule[] = [
  // GREETING & GRATITUDE
  { intent: "greeting", verbs: ["hello", "hi", "hey", "good", "heyy", "hola", "yo"], nouns: ["morning", "afternoon", "evening", "night", "mrng", "evng", "nite"], prefixes: ["", "good ", "hi ", "hey ", "gd "], actionType: "greeting" },
  { intent: "gratitude", verbs: ["thank", "thanks", "thx", "ty", "appreciate", "perfect", "awesome"], nouns: ["you", "it", "help", "that"], prefixes: ["", "thank ", "thanks ", "thx "], actionType: "greeting" },

  // CONTACT – UNIQUE NOUNS ONLY (NO email/mail - these go to delete)
  { intent: "update_contact", verbs: ["update", "edit", "change", "modify", "save", "fix"], nouns: ["contact", "name", "address", "info", "details" ], actionType: "update" },
  { intent: "delete_contact", verbs: ["delete", "remove", "del", "rm", "erase", "clear"], nouns: ["contact", "person", "customer", "client", "lead", "email", "mail"], actionType: "delete" },

  // TASK – UNIQUE NOUNS (ONLY task-related)
  { intent: "update_task", verbs: ["update", "edit", "change", "modify", "mark", "complete"], nouns: ["task", "todo", "reminder", "item", "checklist"], actionType: "update" },
  { intent: "delete_task", verbs: ["delete", "remove", "del", "rm", "clear", "done"], nouns: ["task", "todo", "reminder", "item"], actionType: "delete" },

  // DEAL / SALES – UNIQUE NOUNS ONLY (NO sale/sales - these go to delete)
  { intent: "update_deal", verbs: ["update", "edit", "change", "move", "modify", "close"], nouns: ["deal", "stage", "amount", "probability", "forecast"], actionType: "update" },
  { intent: "delete_deal", verbs: ["delete", "remove", "del", "rm", "cancel"], nouns: ["deal", "opportunity", "opp", "sale", "sales"], actionType: "delete" },

  // REPORT – UNIQUE NOUNS (ONLY report-related)
  { intent: "report_generation", verbs: ["generate", "create", "run", "build", "show", "view", "export", "download", "pull"], nouns: ["report", "rport", "dashboard", "analytics", "metrics", "kpi", "chart", "graph", "pdf", "excel"], actionType: "query" },
  { intent: "update_report", verbs: ["update", "edit", "change", "modify", "refresh", "filter", "adjust", "tweak"], nouns: ["report", "rport", "filter", "date range", "template", "layout", "view"], actionType: "update" },
  { intent: "delete_report", verbs: ["delete", "remove", "del", "rm", "archive", "clear", "trash"], nouns: ["report", "rport", "template", "dashboard"], actionType: "delete" },
  
  // TICKET – UNIQUE NOUNS
  { intent: "create_ticket", verbs: ["create", "open", "report", "submit"], nouns: ["ticket", "bug", "issue", "problem", "support"], actionType: "create" },

  // ERROR – UNIQUE NOUNS
  { intent: "error_handling", verbs: ["error", "failed", "issue", "bug", "not working", "broke", "crash"], nouns: ["failed", "fail", "error", "occurred", "happened", "screen", "button"], actionType: "error" },

  // DATA SYNC
  { intent: "data_sync", verbs: ["sync", "synchronize", "connect", "integrate"], nouns: ["data", "integration", "service"], actionType: "create" },

  // BILLING - UNIQUE NOUNS (billing-specific only)
  { intent: "billing_query", verbs: ["view", "check", "manage", "update", "upgrade"], nouns: ["billing", "bill", "plan", "invoice", "subscription", "payment"], actionType: "read" },

  // CUSTOMER SUMMARY - UNIQUE NOUNS (customer-specific only)
  { intent: "get_customer_summary", verbs: ["show", "view", "get", "display", "see"], nouns: ["customer", "profile", "summary"], actionType: "read" },
]

// SMART & FAST – ONLY 300 PHRASES TOTAL – NO EXPLOSION
const trainingData: TrainingData[] = RULES.flatMap(rule => {
  const phrases: TrainingData[] = []
  const prefixes = rule.prefixes || ["", "how to ", "please "]

  let count = 0
  const max = 18

  for (const verb of rule.verbs) {
    for (const noun of rule.nouns) {
      if (count >= max) break
      for (const prefix of prefixes.slice(0, 2)) {
        if (count >= max) break
        const p = `${prefix}${verb} ${noun}`.trim()
        phrases.push({ phrase: p, intent: rule.intent })
        phrases.push({ phrase: singularizeWithFuzzyFallback(p), intent: rule.intent })
        count++
      }
    }
    if (count >= max) break
  }

  // Fix "good evng" forever
  if (rule.intent === "greeting") {
    ;["good evng", "gd evng", "good mrng", "hlo", "heyy", "wassup", "yo"].forEach(txt => {
      phrases.push({ phrase: txt, intent: "greeting" })
    })
  }

  // Fix short gratitude phrases
  if (rule.intent === "gratitude") {
    ;["ty", "thx", "thanks", "ty ty", "thx u"].forEach(txt => {
      phrases.push({ phrase: txt, intent: "gratitude" })
    })
  }

  if (rule.intent === "update_deal") {
    ;["edit sales", "update sales", "change sales", "modify sales", "edit sale", "update sale"].forEach(txt => {
      phrases.push({ phrase: txt, intent: "update_deal" })
    })
  }

    // ✅ EXPLICIT CUSTOMER PHRASES
  if (rule.intent === "get_customer_summary") {
    ;["customer details", "customer profile", "view customer", "show customer", "customer summary", "get customer"].forEach(txt => {
      phrases.push({ phrase: txt, intent: "get_customer_summary" })
    })
  }

  return phrases
}).filter((v, i, a) => a.findIndex(t => t.phrase === v.phrase) === i) // dedupe

// NO LOGS – SILENT
export { trainingData }